### ISSUE TITLE
Remove banned enchantments from mobs' drop

### ISSUE THREAD

**Issue by SelmanMr** [Dzious/EnchantControl#12]
I've entirely banned some enchants via this plugin, but players still can get those from killing mobs which randomly spawn with enchanted weapons or armor (for example, sharpness is banned, but zombies still spawn with swords on sharpness 3 and they can drop these swords after death). Could you make feature which removes banned enchants from mobs? Thanks for working on this plugin though.

**Comment by TheZennou** [comment]
Definitely needs to be done. He said he'd do it in discord, and hopefully with my weekly reminders he'll get it done, or give up.
Who knows!
For the mean time you can set it to easy, and increase the damage mobs do, with another plugin. It's dirty but it works!

**Comment by Dzious** [comment]
Hi, Fixed with #17. Release today. Thanks for the report
