### ISSUE TITLE
Enchantment limit per group

### ISSUE THREAD

**Issue by TheCiROMG** [Dzious/EnchantControl#14]
Currently, the plugin GENERALIZES the configuration for ALL USERS, I would like to add a part to the configuration, which allows the same, but with 1 special permission, and enchantments per group. 

For example: common users, can use enchantments up to level 8.
                      but payments users, can use stakes up to level 10, basically 
                      
                      Perm : enchantcontrolreforged.enchantlimit.8 (common users)
                      Perm : enchantcontrolreforged.enchantlimit.10 (payments users)

**Comment by Dzious** [comment]
Hi, 
Thanks for your suggestions.

This could be a potential addition for future updates but I won't add it for the moment for two reasons. 

First it's against the Minecraft EULA to make something available only for people who pay for it.

Second it's against [EnchantControl Reforged's License](https://www.github.com/Dzious/EnchantControl/tree/main/LICENSE.md) to make money out of content from the plugin. In other terms you cannot allow only players who pay for it to have access to upper tiers max level.

If more users need it for more legitimate reasons I'll think about adding it but, as I told earlier, for now it won't.

**Comment by TheCiROMG** [comment]
And if instead of seeing it in economic terms, see it in terms of limits?

The use of the plugin has nothing to do with the owner, you can easily make use of the groups and permissions, without other users having an advantage (by the way, the minecraft eula, it runs only for "official" servers, that is, premiums, but almost everyone ignores it)

I will wait in the future for them to add it, since it can be a great advantage, both for the plugin, and for the owner of your server, by putting limits on users

**Comment by Dzious** [comment]
> by the way, the minecraft eula, it runs only for "official" servers, that is, premiums

As far as i'm concerned, you **have to** accept EULA at server startup. If you do not server won't start and this is independant of `online-mode` being `true` ("premium")  or `false` ("crack").

> but almost everyone ignores it 

I don't mind about people ignoring it. As a developer I do not want to help people to make money onto others work especialy if this is not legal / if the developer disagree. 


> And if instead of seeing it in economic terms, see it in terms of limits

I see it in both terms. 
I personnaly don't make any money out of EnchantControl. It's both a choice and an agreement with Arkobat. I want this plugin to be and to stay free. I do not understand why I would allow people to make money out of our work. 
In terms of addition to the plugin I don't feel like it's a huge request. Actually there is only one request for this feature and i have other WIP features with more requests from server admins. 

I close this issue for now and will come back to it later if more users request this feature.
