### ISSUE TITLE
Error when collecting enchantments of levels above 5 in anvil

### ISSUE THREAD

**Issue by TheCiROMG** [Dzious/EnchantControl#15]
### Describe the bug

Apparently, it happens with all combat items in Minecraft (Armor, Weapons, Tools included)

### How to reproduce the bug ?
1. Gather 2 items in the anvil with levels 6 or 8
2. Enchant them (Works)
3. Look at the console

___

### What is your EnchantControl version?
Sadly, I will say, the latest downloadable version of spigot

___

### What is your spigot/craftbukkit version?
Minecraft Purpur 1.16.5 1163

___

### Logs / Files
https://pastebin.com/9Tyhh3uN

1. Your full server startup from the logs\latest.log : 
[latest.log](https://github.com/Dzious/EnchantControl/files/6621462/latest.log)

2. Your EnchantControl config.yml : https://pastebin.com/wRfJPxaZ

3. Your log's error : https://pastebin.com/9Tyhh3uN

**Comment by Dzious** [comment]
Hi, as written in your logs, this is not related to Enchant Control reforged
`Could not pass event InventoryClickEvent to InventoryRollback`
Please refer to the maintainer of `InventoryRollback`
thanks by advance
