### ISSUE TITLE
WTF IS THIS

### ISSUE THREAD

**Issue by TheCiROMG** [Dzious/EnchantControl#8]
### Describe the bug
-

___

### How to reproduce the bug ?
I have no idea the truth, the user does not remember
___

### What is your EnchantControl version?
1.2.4

___

### What is your spigot/craftbukkit version?
PaperMC 1.16.4 346

___

1. Your full server startup from the logs\latest.log : NONE
2. Your EnchantControl config.yml : https://pastebin.com/u6f9dSR2
3. Your log's error : https://pastebin.com/F4iN0M3h

**Comment by Dzious** [comment]
Hi mate, could you try to put a book in an enchantment table and then select one of the enchantments please ? 
Then if the same error occurs once again please update to version 1.2.4

**Comment by Dzious** [comment]
No response in a week. Ticket closed
